name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  NODE_VERSION: '22.x'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true
          run_install: true

      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Deploy to Bunny
        uses: R-J-dev/bunny-deploy@v2.1.1 # Select the version you wish to use
        with:
          access-key: ${{ secrets.BUNNY_ACCESS_KEY }}
          directory-to-upload: './dist'
          storage-endpoint: 'https://storage.bunnycdn.com'
          storage-zone-name: 'daodao'
          storage-zone-password: ${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}
          concurrency: '50' # Make sure to check the docs about concurrency before choosing this setting
          enable-delete-action: true
          enable-purge-pull-zone: true
          pull-zone-id: '5179362'
          replication-timeout: '15000'
          request-timeout: '5000' # optional, defaults to 5000
          retry-limit: '3' # optional, defaults to 3
